### ISSUE TITLE
EOFException when installing

### ISSUE THREAD

**Issue by johnjohndoe** [tabulapdf/tabula-extractor#95]
I cloned v.0.7.6 aka e40f516bc3a7e96987574e067bce7601a4be8e3f to my machine running Ubuntu 14.10. and jruby 1.5.6. Then I run:

> jruby -S gem install tabula-extractor

This fails with the following console output:

```
Exception in thread "main" java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at org.joda.time.tz.ZoneInfoProvider.readZoneInfoMap(ZoneInfoProvider.java:278)
	at org.joda.time.tz.ZoneInfoProvider.loadZoneInfoMap(ZoneInfoProvider.java:256)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:123)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:82)
	at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:490)
	at org.joda.time.DateTimeZone.setProvider0(DateTimeZone.java:444)
	at org.joda.time.DateTimeZone.<clinit>(DateTimeZone.java:116)
	at org.jruby.RubyTime.getLocalTimeZone(RubyTime.java:96)
	at org.jruby.RubyTime$1.allocate(RubyTime.java:171)
	at org.jruby.RubyClass.allocate(RubyClass.java:220)
	at org.jruby.RubyTime.newInstance(RubyTime.java:655)
	at org.jruby.RubyTime$s_method_0_0$RUBYINVOKER$newInstance.call(org/jruby/RubyTime$s_method_0_0$RUBYINVOKER$newInstance.gen:65535)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:289)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:108)
	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:61)
	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:61)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.evalClassDefinitionBody(ASTInterpreter.java:196)
	at org.jruby.ast.ClassNode.interpret(ClassNode.java:141)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
	at org.jruby.Ruby.loadFile(Ruby.java:2553)
	at org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:61)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:671)
	at org.jruby.runtime.load.LoadService.smartLoad(LoadService.java:314)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:357)
	at org.jruby.runtime.load.LoadService.lockAndRequire(LoadService.java:289)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:984)
	at org.jruby.RubyKernel.require(RubyKernel.java:967)
	at org.jruby.RubyKernel$s_method_1_0$RUBYFRAMEDINVOKER$require.call(org/jruby/RubyKernel$s_method_1_0$RUBYFRAMEDINVOKER$require.gen:65535)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:319)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:309)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:148)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
	at org.jruby.Ruby.loadFile(Ruby.java:2553)
	at org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:61)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:671)
	at org.jruby.runtime.load.LoadService.smartLoad(LoadService.java:314)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:357)
	at org.jruby.runtime.load.LoadService.lockAndRequire(LoadService.java:289)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:984)
	at org.jruby.RubyKernel.require(RubyKernel.java:967)
	at org.jruby.RubyKernel$s_method_1_0$RUBYFRAMEDINVOKER$require.call(org/jruby/RubyKernel$s_method_1_0$RUBYFRAMEDINVOKER$require.gen:65535)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:319)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:309)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:148)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:104)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RootNode.interpret(RootNode.java:129)
	at org.jruby.Ruby.loadFile(Ruby.java:2553)
	at org.jruby.runtime.load.ExternalScript.load(ExternalScript.java:61)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:671)
	at org.jruby.runtime.load.LoadService.smartLoad(LoadService.java:314)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:357)
	at org.jruby.runtime.load.LoadService.lockAndRequire(LoadService.java:289)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:984)
	at org.jruby.RubyKernel.require(RubyKernel.java:967)
	at org.jruby.RubyKernel$s_method_1_0$RUBYFRAMEDINVOKER$require.call(org/jruby/RubyKernel$s_method_1_0$RUBYFRAMEDINVOKER$require.gen:65535)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:319)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:309)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:148)
	at usr.lib.jruby.bin.gem.__file__(gem:8)
	at usr.lib.jruby.bin.gem.load(gem)
	at org.jruby.Ruby.runScript(Ruby.java:692)
	at org.jruby.Ruby.runNormally(Ruby.java:575)
	at org.jruby.Ruby.runFromMain(Ruby.java:418)
	at org.jruby.Main.run(Main.java:286)
	at org.jruby.Main.run(Main.java:128)
	at org.jruby.Main.main(Main.java:97)

System.java:-2:in `arraycopy': java.lang.ArrayIndexOutOfBoundsException
	from DefaultResolver.java:111:in `makeTime'
	from DefaultResolver.java:277:in `create'
	from DefaultResolver.java:317:in `handleScalar'
	from DefaultResolver.java:435:in `orgHandler'
	from DefaultResolver.java:455:in `node_import'
	from org/yecht/ruby/DefaultResolver$s_method_1_0$RUBYINVOKER$node_import.gen:65535:in `call'
	from CachingCallSite.java:146:in `call'
	from RubyLoadHandler.java:39:in `handle'
	from Parser.java:300:in `addNode'
	from DefaultYAMLParser.java:676:in `yyparse'
	from Parser.java:290:in `yechtparse'
	from Parser.java:284:in `parse'
	from YParser.java:152:in `load'
	from org/yecht/ruby/YParser$s_method_0_1$RUBYINVOKER$load.gen:65535:in `call'
	from JavaMethod.java:630:in `call'
	from DynamicMethod.java:186:in `call'
	from CachingCallSite.java:309:in `cacheAndCall'
	from CachingCallSite.java:148:in `call'
	from CallOneArgNode.java:57:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from InterpretedMethod.java:180:in `call'
	from DefaultMethod.java:174:in `call'
	from CachingCallSite.java:309:in `cacheAndCall'
	from CachingCallSite.java:148:in `call'
	from CallOneArgNode.java:57:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:180:in `call'
	from DefaultMethod.java:174:in `call'
	from CachingCallSite.java:309:in `cacheAndCall'
	from CachingCallSite.java:148:in `call'
	from CallOneArgNode.java:57:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from RescueNode.java:199:in `executeBody'
	from RescueNode.java:118:in `interpretWithJavaExceptions'
	from RescueNode.java:110:in `interpret'
	from InterpretedMethod.java:180:in `call'
	from DefaultMethod.java:174:in `call'
	from CachingCallSite.java:309:in `cacheAndCall'
	from CachingCallSite.java:148:in `call'
	from FCallOneArgNode.java:36:in `interpret'
	from InstAsgnNode.java:95:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from EnsureNode.java:96:in `interpret'
	from BeginNode.java:83:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from WhenOneArgNode.java:36:in `whenSlowTest'
	from WhenOneArgNode.java:46:in `when'
	from CaseNode.java:133:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from InterpretedBlock.java:373:in `evalBlockBody'
	from InterpretedBlock.java:346:in `yield'
	from InterpretedBlock.java:303:in `yield'
	from Block.java:194:in `yield'
	from YieldNode.java:112:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedBlock.java:373:in `evalBlockBody'
	from InterpretedBlock.java:346:in `yield'
	from InterpretedBlock.java:303:in `yield'
	from Block.java:194:in `yield'
	from RubyKernel.java:1251:in `loop_1_9'
	from org/jruby/RubyKernel$s_method_0_0$RUBYFRAMEDINVOKER$loop_1_9.gen:65535:in `call'
	from CachingCallSite.java:299:in `cacheAndCall'
	from CachingCallSite.java:117:in `callBlock'
	from CachingCallSite.java:132:in `callIter'
	from FCallNoArgBlockNode.java:32:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from InterpretedMethod.java:160:in `call'
	from DefaultMethod.java:166:in `call'
	from CachingCallSite.java:299:in `cacheAndCall'
	from CachingCallSite.java:117:in `callBlock'
	from CachingCallSite.java:122:in `call'
	from CallNoArgBlockNode.java:64:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:242:in `call'
	from DefaultMethod.java:198:in `call'
	from CachingCallSite.java:339:in `cacheAndCall'
	from CachingCallSite.java:197:in `callBlock'
	from CachingCallSite.java:202:in `call'
	from RubyClass.java:819:in `call'
	from DynamicMethod.java:194:in `call'
	from WrapperMethod.java:62:in `call'
	from CachingCallSite.java:329:in `cacheAndCall'
	from CachingCallSite.java:188:in `call'
	from FCallTwoArgNode.java:38:in `interpret'
	from LocalAsgnNode.java:123:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from EnsureNode.java:96:in `interpret'
	from InterpretedMethod.java:242:in `call'
	from DefaultMethod.java:198:in `call'
	from CachingCallSite.java:339:in `cacheAndCall'
	from CachingCallSite.java:197:in `callBlock'
	from CachingCallSite.java:202:in `call'
	from CallTwoArgBlockPassNode.java:62:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:283:in `call'
	from DefaultMethod.java:214:in `call'
	from CachingCallSite.java:359:in `cacheAndCall'
	from CachingCallSite.java:237:in `callBlock'
	from CachingCallSite.java:252:in `callIter'
	from CallThreeArgBlockNode.java:64:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:262:in `call'
	from DefaultMethod.java:206:in `call'
	from CachingCallSite.java:349:in `cacheAndCall'
	from CachingCallSite.java:228:in `call'
	from FCallThreeArgNode.java:40:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from InterpretedBlock.java:373:in `evalBlockBody'
	from InterpretedBlock.java:346:in `yield'
	from InterpretedBlock.java:303:in `yield'
	from Block.java:194:in `yield'
	from RubyIO.java:1106:in `open'
	from RubyKernel.java:283:in `open'
	from org/jruby/RubyKernel$s_method_0_2$RUBYFRAMEDINVOKER$open.gen:65535:in `call'
	from DynamicMethod.java:198:in `call'
	from CachingCallSite.java:339:in `cacheAndCall'
	from CachingCallSite.java:197:in `callBlock'
	from CachingCallSite.java:212:in `callIter'
	from FCallTwoArgBlockNode.java:34:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from IfNode.java:119:in `interpret'
	from IfNode.java:119:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:221:in `call'
	from DefaultMethod.java:190:in `call'
	from CachingCallSite.java:329:in `cacheAndCall'
	from CachingCallSite.java:188:in `call'
	from CallTwoArgNode.java:59:in `interpret'
	from InstAsgnNode.java:95:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from RescueNode.java:199:in `executeBody'
	from RescueNode.java:118:in `interpretWithJavaExceptions'
	from RescueNode.java:110:in `interpret'
	from BeginNode.java:83:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:242:in `call'
	from DefaultMethod.java:198:in `call'
	from CachingCallSite.java:339:in `cacheAndCall'
	from CachingCallSite.java:197:in `callBlock'
	from CachingCallSite.java:202:in `call'
	from RubyClass.java:819:in `call'
	from DynamicMethod.java:194:in `call'
	from CachingCallSite.java:329:in `cacheAndCall'
	from CachingCallSite.java:188:in `call'
	from CallTwoArgNode.java:59:in `interpret'
	from DAsgnNode.java:110:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedBlock.java:373:in `evalBlockBody'
	from InterpretedBlock.java:346:in `yield'
	from InterpretedBlock.java:303:in `yield'
	from Block.java:194:in `yield'
	from RubyArray.java:1630:in `eachCommon'
	from RubyArray.java:1637:in `each'
	from org/jruby/RubyArray$i_method_0_0$RUBYFRAMEDINVOKER$each.gen:65535:in `call'
	from CachingCallSite.java:299:in `cacheAndCall'
	from CachingCallSite.java:117:in `callBlock'
	from CachingCallSite.java:122:in `call'
	from CallNoArgBlockNode.java:64:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:221:in `call'
	from DefaultMethod.java:190:in `call'
	from CachingCallSite.java:329:in `cacheAndCall'
	from CachingCallSite.java:188:in `call'
	from CallTwoArgNode.java:59:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from RescueNode.java:199:in `executeBody'
	from RescueNode.java:118:in `interpretWithJavaExceptions'
	from RescueNode.java:110:in `interpret'
	from BeginNode.java:83:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from InterpretedBlock.java:373:in `evalBlockBody'
	from InterpretedBlock.java:346:in `yield'
	from InterpretedBlock.java:303:in `yield'
	from Block.java:194:in `yield'
	from RubyArray.java:1630:in `eachCommon'
	from RubyArray.java:1637:in `each'
	from org/jruby/RubyArray$i_method_0_0$RUBYFRAMEDINVOKER$each.gen:65535:in `call'
	from CachingCallSite.java:299:in `cacheAndCall'
	from CachingCallSite.java:117:in `callBlock'
	from CachingCallSite.java:122:in `call'
	from CallNoArgBlockNode.java:64:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:139:in `call'
	from DefaultMethod.java:158:in `call'
	from CachingCallSite.java:289:in `cacheAndCall'
	from CachingCallSite.java:108:in `call'
	from VCallNode.java:85:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from IfNode.java:119:in `interpret'
	from IfNode.java:119:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:180:in `call'
	from DefaultMethod.java:174:in `call'
	from CachingCallSite.java:309:in `cacheAndCall'
	from CachingCallSite.java:148:in `call'
	from CallSpecialArgNode.java:67:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from CaseNode.java:138:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:180:in `call'
	from DefaultMethod.java:174:in `call'
	from CachingCallSite.java:309:in `cacheAndCall'
	from CachingCallSite.java:148:in `call'
	from FCallOneArgNode.java:36:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from RescueNode.java:199:in `executeBody'
	from RescueNode.java:118:in `interpretWithJavaExceptions'
	from RescueNode.java:110:in `interpret'
	from InterpretedMethod.java:180:in `call'
	from DefaultMethod.java:174:in `call'
	from CachingCallSite.java:309:in `cacheAndCall'
	from CachingCallSite.java:148:in `call'
	from CallOneArgNode.java:57:in `interpret'
	from NewlineNode.java:104:in `interpret'
	from BlockNode.java:71:in `interpret'
	from InterpretedMethod.java:180:in `call'
	from DefaultMethod.java:174:in `call'
	from CachingCallSite.java:309:in `cacheAndCall'
	from CachingCallSite.java:148:in `call'
	from gem:24:in `rescue_1$RUBY$__rescue___0'
	from gem:23:in `__file__'
	from gem:-1:in `load'
	from Ruby.java:692:in `runScript'
	from Ruby.java:575:in `runNormally'
	from Ruby.java:418:in `runFromMain'
	from Main.java:286:in `run'
	from Main.java:128:in `run'
	from Main.java:97:in `main'
```

**Comment by jeremybmerrill** [comment]
Hey @johnjohndoe: I suspect the issue is that your JRuby is old. Can you try 1.7.15? (I've run into weird issues on various platforms with 1.7.16 and 1.7.19, strangely.)

FWIW I do most of my Tabula development on 14.10, so Ubuntu is equally as supported as Mac (Windows is supported only begrudgingly!).

**Comment by johnjohndoe** [comment]
Yes, this works better. You might wanna add a *.ruby-version* file to the repository defining `jruby-1.7.15`.

**Comment by jeremybmerrill** [comment]
Hi @johnjohndoe: Good idea! I added a .ruby-version just now.

Those warnings should be disabled as of January, in 0f1eee0.

**Comment by johnjohndoe** [comment]
:+1:
